#!/bin/bash
source "./config.sh"

if [ -z "$1" ]; then
 echo "gpadd: gitpkg group requires a name" >&2
elif [ -z "$2" ]; then
 echo "gpadd: gitpkg group requires a contribiutor url" >&2
else
 echo "Adding package group to $source, this should only take a second....."
 cd $source
 mkdir "$1"
 echo "Folder created for new package group....."
 cd "$1" || error "gpadd" "cd"
 echo "Creating source file....."
 if [[ "$1" == !*"-pkg" ]]; then $truef="$1-pkg" else $truef="$1"
 echo $2 > "$1.source"
 echo "Creating package group folder....."
 if ! [ -d $truef ]; then
     echo "Directory not found, assuming new package pack....."
     cd $pkgloc
     mkdir $truef.group
     echo "Package pack created, continuing....."
     cd 
 fi
fi
